### PR TITLE
Fixes/Improvements following helm walkthrough #2

### LINKED ISSUE #299: V3 walkthrough #2 issues
Workload Summary
- [x] Loading Resources indicator v spacing
- [x] Error in console on hover of chart key item
- [x] Stratos Metrics Chart - fails to load svg icon #304

Workloads List (@richard-cox)
- [x] Show chart icon in card 
- [x] Show cluster (which is link) in card (and table?)

Pods Lists (@richard-cox)
- [x] Colourise pod status, do best fit with statuses we know
- [x] Fix display of cluster and namespace columns (don't show when in context of individual cluster/namespace)

Kube Summary (@richard-cox)
- [x] Make three stats at top not evenly spaces... making them aesthetically better

Node List (@richard-cox)
- [x] Remove Pod count from Capacity cell

Namespace List (@richard-cox)
- [x] Hide 'dashboard' column

Side Panel
- [x] Update background of title to match that of title beneath, not top title

Side Panel - Kube
- [x] Make title entity name only
- [x] Remove entity name from content
- [x] make api, kind and if available metrics into single h line
- [x] remove `labels` and `expandedStatus` values from displayed json

General (@richard-cox)
- [x] Ensure all kube namespaces text are not title cases

Create Issues For
- [ ] Kube/Node Summary pages - Show 'pods of interest' as per cf summary (those not 1/1 running)
- [ ] Node Metrics - Drop down searchable filter for metrics
- [ ] Node Metrics - Bug - pod/container labels end in undefined
- [ ] Side panel - kube - monitor obs chain for updates to pod/entity... and if found show button to allow user to see update. do by diff/md5 of obj

### PR DESCRIPTION
**Pull request by richard-cox**
- blocked on #298
- fixes #299

### CODE REVIEW

File: custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.ts [hunk 1]
```diff
@@ -181,43 +179,49 @@ export class KubedashConfigurationComponent implements OnDestroy {
...
+    if (method === 'post') {
+      obs = this.httpClient.post(url, {});
+    } else if (method === 'delete') {
+      obs = this.httpClient.delete(url, {});
+    } else {
+      console.error('Unsupported http method');
+      return;
+    }
+
+    obs.pipe(delay(999999999)).subscribe(() => {
```
Comment (nwmac) [inline custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.ts]: Remove delay

**Review by nwmac — CHANGES_REQUESTED** [review]
One debug delay to remove

**Review by nwmac — APPROVED** [review]
LGTM
